sudo: false
language: python
python:
- '2.7'
env:
  - COUNTRY_NAME='Singapore' REGION_NAME='North' ADM_LEVEL='1'
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# command to run tests
script: nosetests
before_deploy: "echo 'ready?'"
deploy:
  # test pypi
  - provider: pypi
    server: https://testpypi.python.org/pypi
    user: suriyan
    password:
      secure: z6IqUNXNkw87krx4K91PKyQCGUqUb8ohgyVY+8shW57CGD/A9qBEx9mlIN89CkBk/L9wRlq9Mj0W3n3LVIZ4W4GRcEtbvx2PhoRwJirdRyZdayW5ues2gvdmFGtEEiU1jhVvI2yuRtqsYG0RWm+BZJumOL7NRwkrP/yA/i3AysbZDqJzuTM1Q2nWcbtGG9qHrWnicqRYd2pYNe9fXbEUmaRNicCRlTh4wchb3Eqj3p2xTiOecKFr6MhJAT697KRWnUIQ/cPtODRdTsmB+AtraD7gJzwJfWbaMmFdFX9+VkeKLBC7JjpW+Hkcv7pLOTjErp5t03o0JGsfxlzC6RxKZl9ClYQE/XVqzEzHyh3zW2npkOtyhLVdN/OSbCboPBJrwUTg9foEyPeJAdUNNGyj0rLZ0yCFkQd/Uptm7RNUv94B6ibCylWR/dS3hJelSKcoCLgUeHXJlo0Uzd7wciZYeaO9PlIhGWq8D4Zy6GFr14K7JMwL4hzB2nygpDlVboBtsgz8UK90tw7GyVZ8oSndm319g0ykTZZs8i4ILmW1vCPnyXpRSCSRu5GsA/x9CMGZbZx0hm4v2v9n0GFuOwOvw7I01858WYnJklzt3rn28VOJtk4Q6EE0M2IYwAfI93t+iUAQg105WDvEXF90UKKFHqusL56ACNts2w6W0BRiI04=
    on:
      tags: false
      distributions: sdist bdist_wheel
      repo: soodoku/geo_sampling
      branch: public
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  # production pypi
  - provider: pypi
    user: suriyan
    password:
      secure: z6IqUNXNkw87krx4K91PKyQCGUqUb8ohgyVY+8shW57CGD/A9qBEx9mlIN89CkBk/L9wRlq9Mj0W3n3LVIZ4W4GRcEtbvx2PhoRwJirdRyZdayW5ues2gvdmFGtEEiU1jhVvI2yuRtqsYG0RWm+BZJumOL7NRwkrP/yA/i3AysbZDqJzuTM1Q2nWcbtGG9qHrWnicqRYd2pYNe9fXbEUmaRNicCRlTh4wchb3Eqj3p2xTiOecKFr6MhJAT697KRWnUIQ/cPtODRdTsmB+AtraD7gJzwJfWbaMmFdFX9+VkeKLBC7JjpW+Hkcv7pLOTjErp5t03o0JGsfxlzC6RxKZl9ClYQE/XVqzEzHyh3zW2npkOtyhLVdN/OSbCboPBJrwUTg9foEyPeJAdUNNGyj0rLZ0yCFkQd/Uptm7RNUv94B6ibCylWR/dS3hJelSKcoCLgUeHXJlo0Uzd7wciZYeaO9PlIhGWq8D4Zy6GFr14K7JMwL4hzB2nygpDlVboBtsgz8UK90tw7GyVZ8oSndm319g0ykTZZs8i4ILmW1vCPnyXpRSCSRu5GsA/x9CMGZbZx0hm4v2v9n0GFuOwOvw7I01858WYnJklzt3rn28VOJtk4Q6EE0M2IYwAfI93t+iUAQg105WDvEXF90UKKFHqusL56ACNts2w6W0BRiI04=
    on:
      tags: true
      distributions: sdist bdist_wheel
      repo: soodoku/geo_sampling
      branch: public
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
after_deploy:
  - "echo 'after'"
  - "echo 'done'"
