#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Sphinx configuration file for Geo Sampling documentation.

This file was generated by sphinx-quickstart and customized for the Geo Sampling
project.
"""

from pathlib import Path
try:
    import tomllib
except ImportError:
    import tomli as tomllib

# Read project metadata from pyproject.toml
project_root = Path(__file__).parent.parent
pyproject_path = project_root / "pyproject.toml"

with open(pyproject_path, "rb") as f:
    pyproject_data = tomllib.load(f)

project_meta = pyproject_data["project"]

# -- General configuration ------------------------------------------------

extensions = ["sphinx.ext.autodoc"]

templates_path = ["_templates"]

SOURCE_SUFFIX = ".rst"

MASTER_DOC = "index"

PROJECT = project_meta["name"].replace("-", " ").title()
AUTHORS = ", ".join([author["name"] for author in project_meta["authors"]])
COPYRIGHT_INFO = f"2016--2025, {AUTHORS}"
AUTHOR = AUTHORS

VERSION = project_meta["version"]
RELEASE = project_meta["version"]

LANGUAGE = None

EXCLUDE_PATTERNS = ["_build", "Thumbs.db", ".DS_Store"]

PYGMENTS_STYLE = "sphinx"
TODO_INCLUDE_TODOS = False

# -- Options for HTML output ----------------------------------------------

HTML_THEME = "sphinx_rtd_theme"
html_static_path = ["_static"]

HTMLHELP_BASENAME = "Geosamplingdoc"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # 'papersize': 'letterpaper',
    # 'pointsize': '10pt',
    # 'preamble': '',
    # 'figure_align': 'htbp',
}

latex_documents = [
    (MASTER_DOC, "Geosampling.tex", "Geo sampling Documentation",
     COPYRIGHT_INFO, "manual"),
]

# -- Options for manual page output ---------------------------------------

man_pages = [
    (MASTER_DOC, "geosampling", "Geo sampling Documentation",
     [AUTHOR], 1)
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (MASTER_DOC, "Geosampling", "Geo sampling Documentation", AUTHOR,
     "Geosampling", "One line description of project.", "Miscellaneous"),
]
