#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Sphinx configuration file for Geo Sampling documentation.

This file was generated by sphinx-quickstart and customized for the Geo Sampling
project.
"""

# -- General configuration ------------------------------------------------

extensions = ["sphinx.ext.autodoc"]

templates_path = ["_templates"]

SOURCE_SUFFIX = ".rst"

MASTER_DOC = "index"

PROJECT = "Geo sampling"
COPYRIGHT_INFO = "2016--2025, Suriyan Laohaprapanon, Gaurav Sood"
AUTHOR = "Suriyan Laohaprapanon, Gaurav Sood"

VERSION = "0.1.0"
RELEASE = "0.1.0"

LANGUAGE = None

EXCLUDE_PATTERNS = ["_build", "Thumbs.db", ".DS_Store"]

pygments_style = "sphinx"
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

HTML_THEME = "sphinx_rtd_theme"
html_static_path = ["_static"]

HTMLHELP_BASENAME = "Geosamplingdoc"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # 'papersize': 'letterpaper',
    # 'pointsize': '10pt',
    # 'preamble': '',
    # 'figure_align': 'htbp',
}

latex_documents = [
    (MASTER_DOC, "Geosampling.tex", "Geo sampling Documentation",
     COPYRIGHT_INFO, "manual"),
]

# -- Options for manual page output ---------------------------------------

man_pages = [
    (MASTER_DOC, "geosampling", "Geo sampling Documentation",
     [AUTHOR], 1)
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
    (MASTER_DOC, "Geosampling", "Geo sampling Documentation", AUTHOR,
     "Geosampling", "One line description of project.", "Miscellaneous"),
]
